'use client'
// import { Inter } from "next/font/google";
// import "./globals.css";
import Layout from "./components/layouts/Layout"

// const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <Layout>
      <html lang="en">
        <body >{children}</body>
      </html>
    </Layout>
  );
}
